version: "3.8"

services:
  api:
    image: valux-test:production
    build:
      context: ./api
      dockerfile: dockerfile
      target: production
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
