# BUILD
FROM node:16-alpine as development
WORKDIR /home/node/api
COPY package*.json ./
RUN npm i
COPY . .
EXPOSE 3000 9229
CMD npm run start:dev


# PRODUCTION
FROM node:16-alpine as production
WORKDIR /home/node/api
COPY package*.json ./
RUN npm i --only=production
COPY . .
EXPOSE 3000
CMD npm run start:prod
